package drawing;

/**
 * Classe com as medidas de desenho dos componentes.
 * @author Cadore
 *
 */
public class Measures {
	public static int SWITCH_FACE = 40;
	public static int ARROW_LENGTH = 30;
	public static int ARROW_DISTANCE_FROM_SWITCH = 2;
	public static int DISTANCE_BETWEEN_SWITCHES = ARROW_LENGTH + (2 * ARROW_DISTANCE_FROM_SWITCH);
	public static int ARROW_DISTANCE_FROM_SWITCH_BORDER = 13;
	public static int SWITCH_DISTANCE_FROM_PANEL = 20;
	public static int ARROWHEAD_MEASURES = 5;
	public static int ID_DISTANCE_FROM_TOP = 25;
	public static int ID_DISTANCE_FROM_LEFT = 14;
	public static int SEGMENT_BORDER_DISTANCE_FROM_SWITCH = 5;
	public static int WHITE_SPACE = 3;
	public static int SEGMENT_BORDER_DISTANCE_FROM_ARROW = ARROW_DISTANCE_FROM_SWITCH_BORDER + SEGMENT_BORDER_DISTANCE_FROM_SWITCH;
	public static int FINAL_SEGMENT_BORDER_DISTANCE_FROM_SWITCH = SEGMENT_BORDER_DISTANCE_FROM_SWITCH + WHITE_SPACE;
	public static int DISTANCE_BETWEEN_ARROWS = SWITCH_FACE - (2 * ARROW_DISTANCE_FROM_SWITCH_BORDER);
	public static int RESTRICTIONS_WIDTH = SEGMENT_BORDER_DISTANCE_FROM_SWITCH;
	public static int CORNER_RESTRICTION_LENGTH = (DISTANCE_BETWEEN_SWITCHES - (2 * FINAL_SEGMENT_BORDER_DISTANCE_FROM_SWITCH)) / 2;
	public static int FACE_RESTRICTION_LENGHT = SWITCH_FACE + (2 * SEGMENT_BORDER_DISTANCE_FROM_SWITCH);
	public static int RESTRICTION_DISTANCE = ARROW_DISTANCE_FROM_SWITCH;
	public static int FACE_RESTRICTION_INITIAL_DISTANCE = RESTRICTIONS_WIDTH;
	public static int CHARACTER_WIDTH = 6;
	public static int CHARACTER_HEIGHT = 10;
	public static int WEIGHT_DISTANCE_FROM_ARROW = 5;

}
